------------------ Simbolo inicial -----------------

<programa>

-------------------- Terminales --------------------

Palabras reservadas:
    "main"
    "val"
    "if"
    "elif"
    "while"
    "for"
    "return"
    "break"
    "write"
    "read"
    "int"
    "float"
    "boolean"
    "char"
    "string"
    "void"

Operadores aritmeticos:
    Binarios:
        "+"
        "-"
        "*"
        "/"
        "//"
        "mod" (Modulo)
        "pot" (Potencia)

    Unarios:
        "-"
        "++"
        "--"

Operadores relacionales:
    "<"
    ">"
    "<="
    ">="
    "=="

Operadores logicos:
    "λ" (and)
    "θ" (or)
    "Σ" (not)
    
Delimitadores:
    "¿:" (Abre bloque)
    "?:" (Cierra bloque)
    "є:" (Abre parentesis)
    ":э" (Cierra parentesis)
    "ʃ:" (Inicia corchetes)
    ":ʅ" (Cierra corchetes)
    "»" (Cierra expresion)
    "Ͱ" (Asignacion)
    "|" (Comentario de linea)
    "¡" (Abre comentario multilinea)
    "!" (Cierra comentario multilinea)
    "," (Separador para parametros de funcion)

------------------- No Terminales ------------------

------------------- Producciones -------------------